plantManagement/login/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'login'

urlpatterns = [

	url(r'^$',views.indexView,name='home'),
	
	url(r'^register/$',views.UserRegisterView,name='register'),

	url(r'^login/$',views.UserLoginView,name='login'),
]

plantManagement/plantManagement/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('login.urls')),
    url(r'^sensors/', include('sensors.urls')),
]

plantManagement/login/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User)

plantManagement/login/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm,PasswordInput
from .models import *

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password','first_name','last_name')

plantManagement/login/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponseRedirect
from .models import UserProfile
from django.urls import reverse
from django.contrib.auth.models import User
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login,logout
from login.forms import UserForm
from django.views import generic


def indexView(request):
	logout(request)
	template_name='login/home.html'
	return render(request,template_name)

def UserRegisterView(request):
    logout(request)
    if request.method=='POST':
        form=UserForm(request.POST)
        if form.is_valid():
            new_user = User.objects.create_user(**form.cleaned_data)
            new_user_profile = UserProfile
            new_user_profile.userId = new_user
#            new_user_profile.save()
            login(request,new_user)
            return HttpResponseRedirect('/sensors/')
    else:
        form=UserForm()

    return render(request,'login/registration_form.html',{'form':form})                        

def UserLoginView(request):
    logout(request)
    if request.method=='POST':
        form=UserForm(request.POST)
        try:
            username=request.POST.get('username')
            password=request.POST.get('password')
            user = authenticate(username=username,password=password)
            login(request,user)
            return HttpResponseRedirect('/sensors/')
        except Exception:
            return HttpResponseRedirect(reverse('login:login'))
    else:
        form = UserForm()
    return render(request,'login/login_form.html',{'form':form})

plantManagement/login/templates/login/form_template.html
{% load static %}
<!DOCTYPE html>
<html>
<meta charset="UTF-8">
  <title>Sign-up</title>
  <link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
  <link href="https://fonts.googleapis.com/css?family=Nosifer" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

      <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<form action="">

  <div class="container form">

    <h1>Log In / Register</h1>

            <div class="field-wrap">
            <label>
              Username<span class="req">*</span>
            </label>
            <input type="text" required autocomplete="off" name="username" />
          </div>

          <div class="field-wrap">
            <label>
            Password<span class="req">*</span>
            </label>
            <input type="password" required autocomplete="off" name="password"/>
          </div>

          <button type="submit" class="button button-block"/>Submit</button>
  </div>


</form>
  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

  <script  src="{% static 'js/index.js' %}"></script>
</body>
</html>

plantManagement/login/templates/login/home.html
<!DOCTYPE html>
<html>
<head>
	<title>HOME PAGE</title>
<style >
	body{
		background: url('http://www.pptback.com/uploads/pot-plant-backgrounds-powerpoint.jpg');
		background-repeat: no-repeat;
		background-size: cover;
	}
.button {
  display: inline-block;
  padding: 10px 20px;
  font-size: 24px;
  cursor: pointer;
  text-align: center;
  text-decoration: none;
  outline: none;
  color: #fff;
  background-color: black;
  border: none;
  border-radius: 15px;
  box-shadow: 0 9px #999;
}

.button:hover {background-color:grey}

.button:active {
  background-color: grey;
  box-shadow: 0 5px #666;
  transform: translateY(4px);
}
</style>
</head>
</html>
<body>
	<br><br>
	<center>
		<h1 style="color: #286d05">PLANT MONITORING SYSTEM USING IoT</h1>
	
<br/>
  <a href="{% url 'login:login' %}"><button class="button">LOGIN</button></a><br><br><br><br>
  <a href="{% url 'login:register' %}"><button class="button">REGISTER</button></a>
</center>
</center>
</body>

plantManagement/login/templates/login/login_form.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'sensors/style.css' %}" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><img src="https://cdn2.iconfinder.com/data/icons/facebook-svg-icons-1/64/home-128.png" height="25" width="25"></a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    
                </li>
            </ul>


        </div>

    </div>
</nav>



{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}
{% if reg %}
<form class="form-horizontal" role="form" action="{% url 'login:login' %}" method="post" enctype="multipart/form-data">
    {% else %}
    <form class="form-horizontal" role="form" action="{% url 'login:login' %}" method="post" enctype="multipart/form-data">
        {% endif %}
        {% csrf_token %}
        {% include 'login/form_template.html' %}

    </form>
</form>
<!--http://10.0.3.23:8005/sensors/login/-->

plantManagement/login/templates/login/registration_form.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'sensors/style.css' %}" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'login:home' %}"><img src="https://cdn2.iconfinder.com/data/icons/facebook-svg-icons-1/64/home-128.png" height="25" width="25"></a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">

        </div>

    </div>
</nav>



{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}
{% if reg %}
<body background="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQO98EZZ0nreUOURpjWRHP0kz6VX2_4H8cNNvzy_wwQhSeEUgRhVg">
<form class="form-horizontal" role="form" action="{% url 'login:register' %}" method="post" enctype="multipart/form-data">
    {% else %}
    <form class="form-horizontal" role="form" action="{% url 'login:register' %}" method="post" enctype="multipart/form-data">
        {% endif %}
        {% csrf_token %}
        {% include 'login/form_template.html' %}

    </form>
</form>
</body>
<!--http://10.0.3.23:8005/sensors/login/-->