plantManagement/login/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'login'

urlpatterns = [

	url(r'^$',views.indexView,name='home'),
	
	url(r'^register/$',views.UserRegisterView,name='register'),

	url(r'^login/$',views.UserLoginView,name='login'),
]

plantManagement/plantManagement/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('login.urls')),
    url(r'^sensors/', include('sensors.urls')),
]

plantManagement/sensors/urls.py
from django.conf.urls import url																													
from . import views

app_name = 'sensors'

urlpatterns = [
	# homepage
    url(r'^$', views.index, name='index'),
	#temperature
	url(r'^temperature/$',views.temperature, name='temperature'),
	#humidity
	url(r'^humidity/$',views.humidity, name='humidity'),
	#overhead tank
	url(r'^OHT/$',views.OHT, name='OHT'),
	#rain gauge
	url(r'^rain/$',views.rain, name='rain'),
	#weather station
	url(r'^weather/$',views.weather, name='weather'),
	#add new reading
    url(r'^addreading/$', views.add_reading, name='addreading'),
    #display particular plant info
    url(r'^display/(?P<pid>[0-9]+)/$', views.display, name='display'),
    url(r'^weather/display/(?P<pid>[0-9]+)/$', views.display, name='display'),
    #soil moisture
    url(r'^display/(?P<pid1>[0-9]+)/sm/(?P<pid>[0-9]+)/',views.sm, name='sm'),
    url(r'^weather/display/(?P<pid1>[0-9]+)/sm/(?P<pid>[0-9]+)/',views.sm, name='sm'),
    #add new plant
    url(r'^addplant/$', views.addplant, name='addplant'),
    #demo
    url(r'^demo/$', views.demo, name='demo'),   
    #map
    url(r'^map/',views.map, name='map'),
    #about us
    url(r'^about/$', views.about, name='about'),
    # motorControl
    url(r'^control/(?P<pid>[0-9]+)/$', views.motorControl, name='motorControl'),
]

plantManagement/sensors/models.py
from __future__ import unicode_literals
from django.db import models

class plantID(models.Model):
	pid = models.IntegerField(primary_key=True)
	read_time = models.DateTimeField(auto_now = True)
	plantName = models.CharField(max_length = 25, null=True)
	latitude = models.FloatField(default = 13.5548)
	longitude = models.FloatField(default = 80.027)

	def __str__(self):
		display = 'Pid ' + str(self.pid) + 'Name ' + str(self.plantName) + ' Lat ' + str(self.latitude) + ' Long ' + str(self.longitude) + '\n'
		return display

class plant(models.Model):
	pid = models.ForeignKey(plantID, on_delete = models.CASCADE)
	soilMoisture = models.FloatField(null=True)
	read_time = models.DateTimeField(auto_now = True)

	def __str__(self):
		display = 'Plantid' + str(self.pid) + 'Soil moisture ' + str(self.soilMoisture) + '%\n'
		return display

class weatherStation(models.Model):
	read_time = models.DateTimeField(auto_now = True)
	temperature = models.FloatField(default=0)
	humidity = models.FloatField(default=0)
	overHeadTank = models.FloatField(default=0)
	rainGauge = models.FloatField(null=True)

	def __str__(self):
		display = 'Temperature ' + str(self.temperature) + 'C ' + 'Humidity' + str(self.humidity) + '% ' + 'Level of overhead tanks water: ' + str(self.overHeadTank) + 'cm ' + 'Level of rain gauge water: ' + str(self.rainGauge) + 'cm\n'
		return display

plantManagement/sensors/views.py
from .models import *
from django.views.decorators.csrf import csrf_exempt
import json
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.core import serializers
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views import generic
from login.forms import UserForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    template = 'sensors/index.html'
    plantnum = plantID.objects.all()
    print(plantnum)
    data={'username': request.user, 'plantnum': plantnum}
    return render(request, template, data)

@csrf_exempt
def add_reading(request):
    if request.POST.get('plant'):
    	data1 = request.POST.get('plant').split(' ')
    	for n in range(1, len(data1)-3):
    		moisture = plant.objects.create(pid=plantID.objects.get(pid=n), soilMoisture = data1[n+3])
    		moisture.save()
    	weather = weatherStation.objects.create(temperature=data1[0], humidity=data1[1], overHeadTank=data1[2], rainGauge=data1[3])
    	weather.save()
    	return HttpResponse(status=200)
    return  HttpResponse(status=400)

# specific to particular plant requested
@login_required
@csrf_exempt
def display(request, pid):
	moisture = plant.objects.filter(pid=pid)[::-1]
	print(moisture)
	plantDetail = plantID.objects.filter(pid=pid)[::-1]
	w = weatherStation.objects.filter(pk=weatherStation.objects.count())
	weather = weatherStation.objects.get(pk=weatherStation.objects.count())
	T = [weatherStation.objects.get(pk=weatherStation.objects.count()-k).temperature for k in range(0, 11)][::-1]
	H = [weatherStation.objects.get(pk=weatherStation.objects.count()-k).humidity for k in range(0, 11)][::-1]
	OHT = [weatherStation.objects.get(pk=weatherStation.objects.count()-k).overHeadTank for k in range(0, 11)][::-1]
	RG = [weatherStation.objects.get(pk=weatherStation.objects.count()-k).rainGauge for k in range(0, 11)][::-1]
	D = [weatherStation.objects.get(pk=weatherStation.objects.count()-k).read_time.time for k in range(0, 11)][::-1]
	Dt =[weatherStation.objects.get(pk=weatherStation.objects.count()-k).read_time.date for k in range(0, 11)][::-1] 
	if len(moisture) == 0:
		data={'username': request.user, 'w': w ,'sM': "None", 'plantName': plantDetail[0].plantName, 'latitude': plantDetail[0].latitude, 'longitude': plantDetail[0].longitude,  'pid': pid, 'weather': weather,'temperature' : T,'humidity': H, 'overHeadTank': OHT, 'rainGauge': RG,'tm': zip(D,Dt)}
		template = 'sensors/plant.html'
		return render(request, template, data)
	data={'username': request.user,'w': w , 'sM': moisture, 'latitude': plantDetail[0].latitude, 'longitude': plantDetail[0].longitude, 'plantName': plantDetail[0].plantName, 'pid': pid, 'weather': weather,'temperature' : T,'humidity': H, 'overHeadTank': OHT, 'rainGauge': RG,'tm': zip(D,Dt)}
	#print(w)
	template = 'sensors/plant.html'
	return render(request, template, data)

@csrf_exempt
def motorControl(request, pid):
	#plant = plantID.objects.filter(pid=pid)[::-1]
	if request.method=='POST':
		template = loader.get_template('sensors/motorControl.html')
		if request.POST['status'] == 'automatic':
			mode = 'automatic'
			status = "none"
			print(actuator)
		else:
			mode = 'manual'
			status = request.POST['status']
			print(actuator, status)
	context = {
		'pid': pid,
		'mode': mode,
		'status': status,
	}
	return HttpResponse(template.render(context, request))


@login_required
def weather(request):
	if request.method == "GET":
		plantnum = plantID.objects.all()
		weather = weatherStation.objects.get(pk=weatherStation.objects.count())
		T = [weatherStation.objects.get(pk=weatherStation.objects.count()-k).temperature for k in range(0, 11)][::-1]
		H = [weatherStation.objects.get(pk=weatherStation.objects.count()-k).humidity for k in range(0, 11)][::-1]
		OHT = [weatherStation.objects.get(pk=weatherStation.objects.count()-k).overHeadTank for k in range(0, 11)][::-1]
		RG = [weatherStation.objects.get(pk=weatherStation.objects.count()-k).rainGauge for k in range(0, 11)][::-1]
		template = 'sensors/weather.html'
		data={'username': request.user, 'plantnum': plantnum, 'temperature': T, 'humidity': H, 'overHeadTank': OHT, 'rainGauge': RG}
		#print(T, H, OHT, RG)
		return render(request, template, data)

@login_required
@csrf_exempt
def sm(request, pid1, pid):
	print("entered")
	moisture = plant.objects.filter(pid=pid)[::-1]
	print(moisture)
	plantDetail = plantID.objects.filter(pid=pid)[::-1]
	D = [weatherStation.objects.get(pk=weatherStation.objects.count()-k).read_time.time for k in range(0, 11)][::-1]
	Dt =[weatherStation.objects.get(pk=weatherStation.objects.count()-k).read_time.date for k in range(0, 11)][::-1] 
	if len(moisture) == 0:
		data={'username': request.user,'sM': zip("None",D,Dt), 'plantName': plantDetail[0].plantName, 'latitude': plantDetail[0].latitude, 'longitude': plantDetail[0].longitude,  'pid': pid}
		template = 'sensors/sm.html'
		return render(request, template, data)
	data={'username': request.user, 'sM': zip(moisture,D,Dt), 'latitude': plantDetail[0].latitude, 'longitude': plantDetail[0].longitude, 'plantName': plantDetail[0].plantName, 'pid': pid}
	print(moisture)
	template = 'sensors/sm.html'
	return render(request, template, data)

@csrf_exempt
def demo(request):
	template = 'sensors/demo.html'
	return render(request, template)

@csrf_exempt
def about(request):
	template = 'sensors/about.html'
	return render(request, template)

@login_required
@csrf_exempt
def addplant(request):
	if request.method == "POST":
		plantName = request.POST['plantname']
		latitude = request.POST['lat']
		longitude = request.POST['long']
		p = plantID.objects.count()
		plant = plantID.objects.create(pid=p+1, plantName=plantName, latitude=latitude, longitude=longitude)
		plant.save()
		return redirect('sensors:index')
	template = 'sensors/addplant.html'
	return render(request, template)

@login_required
def temperature(request):
	if request.method == "GET":
		weather = weatherStation.objects.get(pk=weatherStation.objects.count())
		T = [weatherStation.objects.get(pk=weatherStation.objects.count()-k).temperature for k in range(0, 11)][::-1]
		D = [weatherStation.objects.get(pk=weatherStation.objects.count()-k).read_time.time for k in range(0, 11)][::-1]
		Dt =[weatherStation.objects.get(pk=weatherStation.objects.count()-k).read_time.date for k in range(0, 11)][::-1] 
		template = 'sensors/temperature.html'
		data={'username': request.user, 'temperature': zip(T, D, Dt)}
		return render(request, template, data)

@login_required
def humidity(request):
	if request.method == "GET":
		weather = weatherStation.objects.get(pk=weatherStation.objects.count())
		H = [weatherStation.objects.get(pk=weatherStation.objects.count()-k).humidity for k in range(0, 11)][::-1]
		D = [weatherStation.objects.get(pk=weatherStation.objects.count()-k).read_time.time for k in range(0, 11)][::-1]
		Dt =[weatherStation.objects.get(pk=weatherStation.objects.count()-k).read_time.date for k in range(0, 11)][::-1] 
		template = 'sensors/humidity.html'
		data={'username': request.user, 'humidity': zip(H, D, Dt)}
		return render(request, template, data)

@login_required
def OHT(request):
	if request.method == "GET":
		weather = weatherStation.objects.get(pk=weatherStation.objects.count())
		OHT = [weatherStation.objects.get(pk=weatherStation.objects.count()-k).overHeadTank for k in range(0, 11)][::-1]
		D = [weatherStation.objects.get(pk=weatherStation.objects.count()-k).read_time.time for k in range(0, 11)][::-1]
		Dt =[weatherStation.objects.get(pk=weatherStation.objects.count()-k).read_time.date for k in range(0, 11)][::-1] 
		template = 'sensors/OHT.html'
		data={'username': request.user, 'oht': zip(OHT, D, Dt)}
		return render(request, template, data)

@login_required
def rain(request):
	if request.method == "GET":
		weather = weatherStation.objects.get(pk=weatherStation.objects.count())
		R = [weatherStation.objects.get(pk=weatherStation.objects.count()-k).rainGauge for k in range(0, 11)][::-1]
		D = [weatherStation.objects.get(pk=weatherStation.objects.count()-k).read_time.time for k in range(0, 11)][::-1]
		Dt =[weatherStation.objects.get(pk=weatherStation.objects.count()-k).read_time.date for k in range(0, 11)][::-1] 
		template = 'sensors/rain.html'
		data={'username': request.user, 'rainLevel': zip(R, D, Dt)}
		print(R, D, Dt)
		return render(request, template, data)

@login_required
def map(request):
    if request.method == 'GET':
    	plantD = plantID.objects.all()
    	num = []
    	lat = []
    	longi = []
    	num2 = []
    	lat2 = []
    	longi2 = []
    	k=0
    	for q in plantD:
    		if(k<2):
	    	    num.append(q.pid)
	    	    lat.append(q.latitude)
	    	    longi.append(q.longitude)
	    	else:
	    		num2.append(q.pid)
	    		lat2.append(q.latitude)
	    		longi2.append(q.longitude)
	    	k=k+1

    	k=len(num)
    	data={'username': request.user,'locate': zip(num,lat,longi),'locate2': zip(num2,lat2,longi2)}
    	template = 'sensors/map.html'
    	print(num,lat,longi)
    	return render(request, template, data)

plantManagement/sensors/templates/sensors/about.html
<!DOCTYPE html>
<html>
<head>
	<title>ABOUT US</title>
	<style type="text/css">
		
		.a{
			background: url('http://www.sepeb.com/background-images-for-websites/background-images-for-websites-016.jpg');
			background-size: cover;
			background-repeat: no-repeat;

		}
		.b{
			background-color:gray;
			height: 750px;
			width: 70%;
		}
		.img-circle {
    border-radius: 50%;
   	border: 7px solid black;
}
	
.p{
	font-size: 50px;
}
.p1{
	font-size: 30px;
}


	</style>
</head>
<body class="a">
	<center>
		<p class="p"><b>ABOUT US</b></p>
		<div class="b">
		<img class="img-circle" src="https://image.ibb.co/gcROk6/image.jpg" width="300px" height="270px">&emsp;&emsp;&emsp;&emsp;&emsp;<img  class="img-circle" src="https://image.ibb.co/b9vG56/IMG_20171121_185409.jpg" width="300px" height="270px">
		&emsp;&emsp;&emsp;&emsp;&emsp;
		<img  class="img-circle" src="https://image.ibb.co/k6tsdR/IMG_1566.jpg" width="300px" height="270px"><p class="p1"><b>PARKHI MOHAN&emsp;&emsp;&emsp;&emsp;&emsp;MAHESHWARI K&emsp;&emsp;&emsp;&emsp;&emsp;SRI HARSHITHA K</b></p>
		<img class="img-circle"  src="https://image.ibb.co/bKx7Cm/IMG_1569.jpg" width="300px" height="270px">&emsp;&emsp;&emsp;&emsp;&emsp;<img class="img-circle"  src="https://image.ibb.co/c7ZnCm/IMG_20160805_WA0000.jpg" width="300px" height="270px">&emsp;&emsp;&emsp;&emsp;&emsp;
		<img class="img-circle"  src="https://image.ibb.co/c7ZnCm/IMG_20160805_WA0000.jpg" width="300px" height="270px">
		<p class="p1"><b>SREE PRAGNA V&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;MOUNIKA C&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;         DHARANI M</b></p>
	</div>
</center>
</body>
</html>

plantManagement/sensors/templates/sensors/controlPage.html
<!DOCTYPE html>
<html>
<head>
	<title>CONTROLLER PAGE</title>
</head>
<body>
	<form action="" method="post">{% csrf_token %}
		<input type="submit" name="on" value="on"/>
		<input type="submit" name="off" value="off"/>
	</form>
	}
</body>
</html>

plantManagement/sensors/templates/sensors/plant.html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<title>PLANT MONITORING SYSTEM</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<meta http-equiv="refresh" content="15">
<style>
html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
</style>
<body class="w3-light-grey">



<!-- Top container -->
<div class="w3-bar w3-top w3-black w3-large" style="z-index:4">
  <!--<button class="w3-bar-item w3-button w3-hide-large w3-hover-none w3-hover-text-light-grey" onclick="w3_open();"><i class="fa fa-bars"></i> &nbsp;Menu</button>-->
  <span class="w3-bar-item w3-left">PLANT MONITORING SYSTEM</span>
</div>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-black w3-animate-left" style="z-index:3;width:300px;" id="mySidebar">
  <div class="w3-container w3-row">
    <div class="w3-col s4">
      <img src="https://cdn2.iconfinder.com/data/icons/snipicons/500/user-64.png" class="w3-circle w3-margin-right" style="width:80px">
    </div>
    <div class="w3-col s8 w3-bar">
      <br><span> &nbsp;&nbsp;Welcome <strong><center>{{ username }} </center></strong></span><br>
    </div>
  </div>
  <div class="w3-container">
    <h5>Dashboard</h5>
  </div>
  <div class="w3-bar-block">
    <a href="{% url 'sensors:index' %}" class="w3-bar-item w3-button w3-padding"><img src="https://cdn3.iconfinder.com/data/icons/tango-icon-library/48/go-home-32.png">&nbsp; HOME</a>
    <a href="{% url 'sensors:weather' %}" class="w3-bar-item w3-button w3-padding"><img src="https://cdn2.iconfinder.com/data/icons/freecns-cumulus/32/519842-54_Sun-32.png">&nbsp; WEATHER STATION</a>
    <a href="{% url 'sensors:map' %}" class="w3-bar-item w3-button w3-padding"><img src="https://cdn1.iconfinder.com/data/icons/location-2/512/map-32.png">&nbsp; MAP</a>
    <a href="{% url 'sensors:demo' %}" class="w3-bar-item w3-button w3-padding"><img src="https://cdn4.iconfinder.com/data/icons/flatron-set-2/512/movie-32.png">&nbsp; DEMO</a>
    <a href="{% url 'sensors:about' %}" class="w3-bar-item w3-button w3-padding"><img src="https://cdn3.iconfinder.com/data/icons/musthave/32/Information.png">&nbsp; ABOUT US</a>
    <a href="{% url 'login:home' %}" class="w3-bar-item w3-button w3-padding"><img src="https://cdn2.iconfinder.com/data/icons/flat-style-svg-icons-part-1/512/user_logout_man-32.png">&nbsp; LOGOUT</a>
    <br><br>
  </div>
</nav>


<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:300px;margin-top:43px;background-color: #DCDCDC">

  <!-- Header -->
  <header class="w3-container" style="padding-top:0px">
    <h5><b><i class="fa fa-dashboard"></i> Dashboard: Plant {{ pid }} - {{ plantName }}</b></h5>
  </header>

  <div class="w3-row-padding w3-margin-bottom">
    <div class="w3-quarter" style="width : 33%;">
      <div class="w3-container w3-red w3-padding-14">
        <div class="w3-left"><img src="https://cdn2.iconfinder.com/data/icons/weather-color-2/500/weather-19-48.png"></div>
        <div class="w3-right">
          <h3 id="tempd"></h3>
          <script type="text/javascript">
         var h;
          {% for i in temperature %}
            { h= "{{ i }}" }
          {% endfor %}
      document.getElementById("tempd").innerHTML = h;
        </script>
        </div>
        <div class="w3-clear"></div>
        <a href="{% url 'sensors:temperature' %}"><h5>TEMPERATURE</h5></a>
      </div>
    </div>
       <div class="w3-quarter" style="width : 33%">
      <div class="w3-container w3-indigo w3-padding-14">
        <div class="w3-left"><img src="https://cdn4.iconfinder.com/data/icons/weather-conditions/512/medium_rain-48.png"></div>
        <div class="w3-right">
        <h3 id="humidd"></h3>
        <script type="text/javascript">
          var h;
          {% for t in humidity %}
        { h= "{{ t }}" }
      {% endfor %}
      document.getElementById("humidd").innerHTML = h;
        </script>
        </div>
        <div class="w3-clear"></div>
        <a href="{% url 'sensors:humidity' %}"><h5>HUMIDITY</h5></a>
      </div>
    </div>
     <div class="w3-quarter" style="width :33%">
      <div class="w3-container w3-teal w3-padding-14">
        <div class="w3-left"><img src="https://cdn3.iconfinder.com/data/icons/flat-icons-web/40/Rain-48.png"></div>
        <div class="w3-right">
         <h3 id="raind"></h3>
          <script type="text/javascript">
          var h;
          {% for t in rainGauge %}
        { h= "{{ t }}" }
      {% endfor %}
      document.getElementById("raind").innerHTML = h;
        </script>
        </div>
        <div class="w3-clear"></div>
        <a href="{% url 'sensors:rain' %}"><h5>RAIN LEVEL</h5></a>
      </div>
    </div>
  </div><br>

  <div class="w3-row-padding w3-margin-bottom">
    <div class="w3-quarter" style="width : 33%">
      <div class="w3-container w3-blue w3-padding-14">
        <div class="w3-left"><img src="https://cdn1.iconfinder.com/data/icons/icons-for-a-site-1/64/advantage_eco_friendly-48.png"></div>
        <div class="w3-right">
          <h3 id="soild"></h3>
        <script type="text/javascript">
          var h;
          {% for t in sM %}
        { h = "{{ t.soilMoisture }}" }
      {% endfor %}
        var n = "";
        var c = n.localeCompare(h); 
        if (c == '0'){
          h="Plant not monitored";
        }
      document.getElementById("soild").innerHTML = h;
        </script>
        </div>
        <div class="w3-clear"></div>
        <a href="sm/{{pid}}/"><h5>SOIL MOISTURE</h5></a>
      </div>
    </div>
     <div class="w3-quarter" style="width : 33%">
      <div class="w3-container w3-brown w3-text-white w3-padding-14">
        <div class="w3-left"><img src="https://cdn2.iconfinder.com/data/icons/snipicons/500/battery-third-48.png" width="40px" height="40px"></div>
        <div class="w3-right">
          <h3 id="tankd"></h3>
        <script type="text/javascript">
          var h;
          {% for t in overHeadTank %}
        { h= "{{ t }}" }
      {% endfor %}
      document.getElementById("tankd").innerHTML = h;
        </script>
        </div>
        <div class="w3-clear"></div>
        <a href="{% url 'sensors:OHT' %}"><h5>TANK LEVEL</h5></a>
      </div>
    </div>
    <div class="w3-quarter" style="width : 33%">
      <div class="w3-container w3-orange w3-text-white w3-padding-14">
        <div class="w3-left"><img src="https://cdn3.iconfinder.com/data/icons/colorful-electronic-parts/108/electronicparts-05-48.png"></div>
        <div class="w3-right">
          <h3 id="actuatord"></h3>
            <script type="text/javascript">
            var h1; //check for monitored
            var h2; //check soil moisture reading
            var h3; //check rain gauge reading
            var h="ON";
            {% for t in sM %}
                h2= {{ t.soilMoisture }}
            {% endfor %}
            {% for t in rainGauge %}
                h3 = {{ t }}
            {% endfor %}
            if ( h2 > 20 || h3 >= 10 ){
               h="OFF";
            }
            {% for t in sM %}
               { h1 = "{{ t.soilMoisture }}" }
            {% endfor %}
            var n = "";
            var c = n.localeCompare(h1); 
            if (c == '0'){
              h="Plant not monitored";
            }
            document.getElementById("actuatord").innerHTML=h;
            </script>
        </div>
        <div class="w3-clear"></div>
        <h5><u>ACTUATOR STATE</u></h5>
      </div>
    </div>
  </div>
<div class="w3-panel">
    <div class="w3-row-padding" style="margin:0 -16px">
      <div class="w3-twothird">
        <h3 style="color: black">&nbsp;&nbsp;GRAPHS</h3>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>

<div id="container" style="width: 1180px; height: 400px; margin: 0 auto"></div>
<script type="text/javascript">
  Highcharts.chart('container', {
    chart: {
        type: 'areaspline'
    },
    title: {
        text: 'Real Time Sensor Readings'
    },
    legend: {
        layout: 'vertical',
        align: 'left',
        verticalAlign: 'top',
        x: 150,
        y: 100,
        floating: true,
        borderWidth: 1,
        backgroundColor: (Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'
    },
    xAxis: {
        categories: [
            {% for i, j in tm %}
               "{{ i }}{{ j }}" ,
            {% endfor %}
        ]
    },
    yAxis: {
        title: {
            text: 'Sensor Readings'
        }
    },
    tooltip: {
        shared: true,
        valueSuffix: ' units'
    },
    credits: {
        enabled: false
    },
    plotOptions: {
        areaspline: {
            fillOpacity: 0.3
        }
    },
    series: [
      {
          name: 'Humidity',
          data:[
          {% for t in humidity %}
              {{ t }},
          {% endfor %}],
      },
      {
          name: 'Temperature',
          data:[
          {% for i in temperature %}
              {{ i }},
          {% endfor %}],
      },
      {
          name: 'Soil Moisture',
          data:[
          {% for t in sM %}
              {{ t.soilMoisture }},
          {% endfor %}],
      },
      {
          name: 'Over Head Tank',
          data:[
          {% for t in overHeadTank %}
              {{ t }},
          {% endfor %}],
      },
      {
          name: 'Rain Fall',
          data:[
          {% for t in rainGauge %}
              {{ t }},
          {% endfor %}],
      }
    ]
});
</script>
      </div>
    </div>
  </div>
  <hr>
</div>

<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
    if (mySidebar.style.display === 'block') {
        mySidebar.style.display = 'none';
        overlayBg.style.display = "none";
    } else {
        mySidebar.style.display = 'block';
        overlayBg.style.display = "block";
    }
}

// Close the sidebar with the close button
function w3_close() {
    mySidebar.style.display = "none";
    overlayBg.style.display = "none";
}
</script>
</body>
</html>